blueprint:
  name: Zigbee2MQTT - Tuya 1 to 4 Buttons (Z2M Legacy Action Support)
  description: >
    Zigbee2MQTT Tuya 1–4 button remotes with legacy_action_sensor: true enabled.
    Works with remotes publishing an "action" attribute like "1_single", "2_hold", etc.
  domain: automation
  input:
    mode:
      name: Automation Mode
      description: https://www.home-assistant.io/docs/automation/modes/
      default: parallel
      selector:
        select:
          mode: dropdown
          options:
            - single
            - restart
            - queued
            - parallel
    remote:
      name: Switch entity
      description: The entity from Zigbee2MQTT 
      selector:
        entity: {}
    button_1_short_press:
      name: Single Press - Button 1
      default: []
      selector:
        action: {}
    button_1_double_press:
      name: Double Press - Button 1
      default: []
      selector:
        action: {}
    button_1_hold:
      name: Hold - Button 1
      default: []
      selector:
        action: {}
    button_2_short_press:
      name: Single Press - Button 2
      default: []
      selector:
        action: {}
    button_2_double_press:
      name: Double Press - Button 2
      default: []
      selector:
        action: {}
    button_2_hold:
      name: Hold - Button 2
      default: []
      selector:
        action: {}
    button_3_short_press:
      name: Single Press - Button 3
      default: []
      selector:
        action: {}
    button_3_double_press:
      name: Double Press - Button 3
      default: []
      selector:
        action: {}
    button_3_hold:
      name: Hold - Button 3
      default: []
      selector:
        action: {}
    button_4_short_press:
      name: Single Press - Button 4
      default: []
      selector:
        action: {}
    button_4_double_press:
      name: Double Press - Button 4
      default: []
      selector:
        action: {}
    button_4_hold:
      name: Hold - Button 4
      default: []
      selector:
        action: {}

mode: !input mode
max_exceeded: silent

trigger:
  - platform: state
    entity_id: !input remote
    attribute: action

condition: []

action:
  - variables:
      event_type: "{{ trigger.to_state.attributes.action | default('') }}"
  - choose:
      - conditions: "{{ event_type == '1_single' }}"
        sequence: !input button_1_short_press
      - conditions: "{{ event_type == '1_double' }}"
        sequence: !input button_1_double_press
      - conditions: "{{ event_type == '1_hold' }}"
        sequence: !input button_1_hold
      - conditions: "{{ event_type == '2_single' }}"
        sequence: !input button_2_short_press
      - conditions: "{{ event_type == '2_double' }}"
        sequence: !input button_2_double_press
      - conditions: "{{ event_type == '2_hold' }}"
        sequence: !input button_2_hold
      - conditions: "{{ event_type == '3_single' }}"
        sequence: !input button_3_short_press
      - conditions: "{{ event_type == '3_double' }}"
        sequence: !input button_3_double_press
      - conditions: "{{ event_type == '3_hold' }}"
        sequence: !input button_3_hold
      - conditions: "{{ event_type == '4_single' }}"
        sequence: !input button_4_short_press
      - conditions: "{{ event_type == '4_double' }}"
        sequence: !input button_4_double_press
      - conditions: "{{ event_type == '4_hold' }}"
        sequence: !input button_4_hold
