blueprint:
  name: Zigbee2MQTT - TS0044 (Device Trigger)
  description: >
    Für Tuya TS0044 Schalter (4 Tasten) via Zigbee2MQTT mit Geräteintegration in Home Assistant.
    Nutzt den eingebauten "device"-Trigger mit den Aktionen: 1–4 und single, double, hold.
    KEIN legacy_action_sensor notwendig.
  domain: automation
  input:
    remote:
      name: TS0044 Gerät
      description: Das Zigbee-Gerät (muss in HA als Gerät erscheinen)
      selector:
        device:
          integration: mqtt
    button_1_single:
      name: Button 1 - Single Press
      default: []
      selector:
        action: {}
    button_1_double:
      name: Button 1 - Double Press
      default: []
      selector:
        action: {}
    button_1_hold:
      name: Button 1 - Hold
      default: []
      selector:
        action: {}
    button_2_single:
      name: Button 2 - Single Press
      default: []
      selector:
        action: {}
    button_2_double:
      name: Button 2 - Double Press
      default: []
      selector:
        action: {}
    button_2_hold:
      name: Button 2 - Hold
      default: []
      selector:
        action: {}
    button_3_single:
      name: Button 3 - Single Press
      default: []
      selector:
        action: {}
    button_3_double:
      name: Button 3 - Double Press
      default: []
      selector:
        action: {}
    button_3_hold:
      name: Button 3 - Hold
      default: []
      selector:
        action: {}
    button_4_single:
      name: Button 4 - Single Press
      default: []
      selector:
        action: {}
    button_4_double:
      name: Button 4 - Double Press
      default: []
      selector:
        action: {}
    button_4_hold:
      name: Button 4 - Hold
      default: []
      selector:
        action: {}

mode: parallel
max_exceeded: silent

trigger:
  - platform: device
    device_id: !input remote
    domain: mqtt
    type: action
    subtype: 1_single
    id: b1_single
  - platform: device
    device_id: !input remote
    domain: mqtt
    type: action
    subtype: 1_double
    id: b1_double
  - platform: device
    device_id: !input remote
    domain: mqtt
    type: action
    subtype: 1_hold
    id: b1_hold

  - platform: device
    device_id: !input remote
    domain: mqtt
    type: action
    subtype: 2_single
    id: b2_single
  - platform: device
    device_id: !input remote
    domain: mqtt
    type: action
    subtype: 2_double
    id: b2_double
  - platform: device
    device_id: !input remote
    domain: mqtt
    type: action
    subtype: 2_hold
    id: b2_hold

  - platform: device
    device_id: !input remote
    domain: mqtt
    type: action
    subtype: 3_single
    id: b3_single
  - platform: device
    device_id: !input remote
    domain: mqtt
    type: action
    subtype: 3_double
    id: b3_double
  - platform: device
    device_id: !input remote
    domain: mqtt
    type: action
    subtype: 3_hold
    id: b3_hold

  - platform: device
    device_id: !input remote
    domain: mqtt
    type: action
    subtype: 4_single
    id: b4_single
  - platform: device
    device_id: !input remote
    domain: mqtt
    type: action
    subtype: 4_double
    id: b4_double
  - platform: device
    device_id: !input remote
    domain: mqtt
    type: action
    subtype: 4_hold
    id: b4_hold

action:
  - choose:
      - conditions:
          - condition: trigger
            id: b1_single
        sequence: !input button_1_single
      - conditions:
          - condition: trigger
            id: b1_double
        sequence: !input button_1_double
      - conditions:
          - condition: trigger
            id: b1_hold
        sequence: !input button_1_hold

      - conditions:
          - condition: trigger
            id: b2_single
        sequence: !input button_2_single
      - conditions:
          - condition: trigger
            id: b2_double
        sequence: !input button_2_double
      - conditions:
          - condition: trigger
            id: b2_hold
        sequence: !input button_2_hold

      - conditions:
          - condition: trigger
            id: b3_single
        sequence: !input button_3_single
      - conditions:
          - condition: trigger
            id: b3_double
        sequence: !input button_3_double
      - conditions:
          - condition: trigger
            id: b3_hold
        sequence: !input button_3_hold

      - conditions:
          - condition: trigger
            id: b4_single
        sequence: !input button_4_single
      - conditions:
          - condition: trigger
            id: b4_double
        sequence: !input button_4_double
      - conditions:
          - condition: trigger
            id: b4_hold
        sequence: !input button_4_hold
