blueprint:
  name: Zigbee2MQTT - TS0044 (MQTT-Event, keine legacy sensor)
  description: >
    Reagiere direkt auf MQTT-Events von Zigbee2MQTT, z. B. TS0044 (4-Tasten-Tuya-Schalter).
    Benötigt KEIN legacy_action_sensor. Unterstützt 1–4 Tasten mit single, double, hold Aktionen.
  domain: automation
  input:
    mode:
      name: Automation Mode
      default: parallel
      selector:
        select:
          options:
            - single
            - restart
            - queued
            - parallel
    device_topic:
      name: Zigbee2MQTT Topic
      description: Topic des Geräts (z. B. zigbee2mqtt/TS0044)
      selector:
        text:
    button_1_short_press:
      name: Button 1 - Single Press
      default: []
      selector:
        action: {}
    button_1_double_press:
      name: Button 1 - Double Press
      default: []
      selector:
        action: {}
    button_1_hold:
      name: Button 1 - Hold
      default: []
      selector:
        action: {}
    button_2_short_press:
      name: Button 2 - Single Press
      default: []
      selector:
        action: {}
    button_2_double_press:
      name: Button 2 - Double Press
      default: []
      selector:
        action: {}
    button_2_hold:
      name: Button 2 - Hold
      default: []
      selector:
        action: {}
    button_3_short_press:
      name: Button 3 - Single Press
      default: []
      selector:
        action: {}
    button_3_double_press:
      name: Button 3 - Double Press
      default: []
      selector:
        action: {}
    button_3_hold:
      name: Button 3 - Hold
      default: []
      selector:
        action: {}
    button_4_short_press:
      name: Button 4 - Single Press
      default: []
      selector:
        action: {}
    button_4_double_press:
      name: Button 4 - Double Press
      default: []
      selector:
        action: {}
    button_4_hold:
      name: Button 4 - Hold
      default: []
      selector:
        action: {}

mode: !input mode
max_exceeded: silent

trigger:
  - platform: event
    event_type: mqtt
    event_data:
      topic: !input device_topic

variables:
  action: "{{ trigger.event.data.payload_json.action | default('') }}"

action:
  - choose:
      - conditions: "{{ action == '1_single' }}"
        sequence: !input button_1_short_press
      - conditions: "{{ action == '1_double' }}"
        sequence: !input button_1_double_press
      - conditions: "{{ action == '1_hold' }}"
        sequence: !input button_1_hold
      - conditions: "{{ action == '2_single' }}"
        sequence: !input button_2_short_press
      - conditions: "{{ action == '2_double' }}"
        sequence: !input button_2_double_press
      - conditions: "{{ action == '2_hold' }}"
        sequence: !input button_2_hold
      - conditions: "{{ action == '3_single' }}"
        sequence: !input button_3_short_press
      - conditions: "{{ action == '3_double' }}"
        sequence: !input button_3_double_press
      - conditions: "{{ action == '3_hold' }}"
        sequence: !input button_3_hold
      - conditions: "{{ action == '4_single' }}"
        sequence: !input button_4_short_press
      - conditions: "{{ action == '4_double' }}"
        sequence: !input button_4_double_press
      - conditions: "{{ action == '4_hold' }}"
        sequence: !input button_4_hold
